src/frameworks/error-logger/main/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Apex errors and can be used as a general logger to track integration callouts and callins.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Err-{0}</displayFormat>
        <label>Error Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/frameworks/error-logger/main/objects/Error_Log__c/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <description>Additional Information logged by the developer</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Additional Information logged by the developer</inlineHelpText>
    <label>Additional Info</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log__c/fields/Caller__c.field-meta.xml
<CustomField>
    <fullName>Caller__c</fullName>
    <description>The class/flow which was involved for this error.
PLANHUB-114531.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Caller</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log__c/fields/DML_Exception_Details__c.field-meta.xml
<CustomField>
    <fullName>DML_Exception_Details__c</fullName>
    <description>List and details of all DML exceptions including the record ID and fields that errored</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>List and details of all DML exceptions including the record ID and fields that errored</inlineHelpText>
    <label>DML Exception Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/error-logger/main/objects/Error_Log__c/fields/Error_Type__c.field-meta.xml
<CustomField>
    <fullName>Error_Type__c</fullName>
    <description>Returns the type of exception, such as DmlException, ListException, MathException, and so on</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Returns the type of exception, such as DmlException, ListException, MathException, and so on</inlineHelpText>
    <label>Error Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log__c/fields/Http_End_Point__c.field-meta.xml
<CustomField>
    <fullName>Http_End_Point__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Http End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log__c/fields/Http_Method__c.field-meta.xml
<CustomField>
    <fullName>Http_Method__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Http Method</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log__c/fields/Http_Request__c.field-meta.xml
<CustomField>
    <fullName>Http_Request__c</fullName>
    <description>This field stores request payload</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>Http Request Payload</inlineHelpText>
    <label>Http Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log__c/fields/Http_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Http_Status_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Http Status Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/frameworks/error-logger/main/objects/Error_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The error message and stack trace for the error</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The error message and stack trace for the error</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>The involved records e.g. Account Id, Financial Account Id, etc
PLANHUB-114531</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log__c/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who initiated the action that caused the error</description>
    <inlineHelpText>User who initiated the action that caused the error</inlineHelpText>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/frameworks/error-logger/main/objects/Error_Log__c/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <description>Short description for the error, (e.g. OBR Submission Error: Create Request Failed: DUPLICATE_CUSTODIAN_ACCOUNT_ID) will be easy for reporting and querying.
PLANHUB-114531</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Short Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/Error_Log_Event__e.object-meta.xml
<CustomObject>
    <description>AP-86705: Create Salesforce platform events for creating error logs in salesforce.</description>
    <label>Error Log Event</label>
    <pluralLabel>Error Log Events</pluralLabel>
</CustomObject>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <description>AP-86705: Create Salesforce platform events for creating error logs in salesforce.</description>
    <label>Additional Info</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/fields/Caller__c.field-meta.xml
<CustomField>
    <fullName>Caller__c</fullName>
    <description>The class/flow which was involved for this error.
PLANHUB-114531</description>
    <label>Caller</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/fields/DML_Exception_Details__c.field-meta.xml
<CustomField>
    <fullName>DML_Exception_Details__c</fullName>
    <description>AP-86705: Create Salesforce platform events for creating error logs in salesforce.</description>
    <label>DML Exception Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/fields/Error_Type__c.field-meta.xml
<CustomField>
    <fullName>Error_Type__c</fullName>
    <description>AP-86705: Create Salesforce platform events for creating error logs in salesforce.</description>
    <label>Error Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/error-logger/main/objects/Error_Log_Event__e/fields/Http_End_Point__c.field-meta.xml
<CustomField>
    <fullName>Http_End_Point__c</fullName>
    <label>Http End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/fields/Http_Method__c.field-meta.xml
<CustomField>
    <fullName>Http_Method__c</fullName>
    <label>Http Method</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/frameworks/error-logger/main/objects/Error_Log_Event__e/fields/Http_Request__c.field-meta.xml
<CustomField>
    <fullName>Http_Request__c</fullName>
    <label>Http Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/fields/Http_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Http_Status_Code__c</fullName>
    <label>Http Status Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>AP-86705: Create Salesforce platform events for creating error logs in salesforce.</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/error-logger/main/objects/Error_Log_Event__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>The involved records e.g. Account Id, Financial Account Id, etc
PLANHUB-114531</description>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <description>AP-86705: Create Salesforce platform events for creating error logs in salesforce.</description>
    <label>Running User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <description>Short description for the error, (e.g. OBR Submission Error: Create Request Failed: DUPLICATE_CUSTODIAN_ACCOUNT_ID) will be easy for reporting and querying.
PLANHUB-114531</description>
    <label>Short Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/classes/ErrorLogger.cls
public class ErrorLogger {
    
    //Marking this flag as true during execution would not rethrow the exception and would let the user code handle the messaging.
    public static boolean suppressException = false;
    
    @TestVisible private static boolean isTestRun = false;

    private static String strError;
    
    public static void logError(Exception ex) {
        logError(ex, null);
    }
    
    public static void  logError(Exception ex, String addInfo) {
        logError(new ErrorInfo(null,null,null,addInfo), ex);
    }
    
    public static void logError(String error) {
        logError(new LoggedException(error));
    }

    //PLANHUB-114531 - Capture more information into Error Log
    public static void logDetailedError(String error, String recId, String callerInstance, Exception ex) {
        Exception newEx = ex;
        if(ex == null && String.isNotBlank(error)){
            newEx = new LoggedException(error);
        }
        String trimmedError = error.length() > 255 ? error.substring(0, 255) : error;
        ErrorLogger.ErrorInfo errInfo = new ErrorLogger.ErrorInfo(trimmedError,recId,callerInstance,error);
        ErrorLogger.logError(errInfo,newEx);
    }
    
    public static void logError(ErrorInfo info, Exception ex){
        Error_Log__c errorLog = new Error_Log__c();
        errorLog.Running_User__c = UserInfo.getUserId();
        errorLog.Error_Type__c = ex.getTypeName();
        errorLog.Short_Description__c = info.shortDesc;// != null ? info.shortDesc : '';
        errorLog.Record_Id__c = info.recordId != null ? info.recordId : '';
        errorLog.Caller__c = info.caller != null ? info.caller : '';
        errorLog.Message__c = ex.getMessage()+'\r\nStack Trace\r\n------------\r\n'+ex.getStackTraceString()+'.';
        
        if(String.isNotBlank(info.addInfo) && info.addInfo.length() > Constant.TEXTAREA_LONG_MAX_LENGTH){
            info.addInfo = info.addInfo.substring(0, Constant.TEXTAREA_LONG_MAX_LENGTH);    
        }
        
        errorLog.Additional_Info__c = info.addInfo;
        logSystemDmlException(errorLog, ex);

        publishErrorLogEvent(errorLog);
        
        if(Test.isRunningTest()){
            isTestRun = true;
        }
        
        if(suppressException == false){
            throw ex;
        }
    }

    @TestVisible
    private static void logSystemDmlException(Error_Log__c errorLog, Exception ex){
        if (('System.DmlException').equals(errorLog.Error_Type__c)) {
            errorLog.DML_Exception_Details__c = '';
            
            for (Integer i = 0; i < ex.getNumDml(); i++) {
                errorLog.DML_Exception_Details__c+= 'Record ID: '+ex.getDmlId(i) +
                    +' Error: ['+ex.getDmlType(i)+' - '+ex.getDmlFields(i)+'] \r\n'+ ex.getDmlMessage(i)
                    +'\r\n\r\n';
            }
            String strDMLExceptionDetails = errorLog.DML_Exception_Details__c;
            if(String.isNotBlank(strDMLExceptionDetails) && strDMLExceptionDetails.length() > Constant.TEXTAREA_LONG_MAX_LENGTH){
                errorLog.DML_Exception_Details__c = strDMLExceptionDetails.substring(0, Constant.TEXTAREA_LONG_MAX_LENGTH);
            }
        }  
        
    }
    
    private static void publishErrorLogEvent(Error_Log__c errorLog){
        Error_Log_Event__e anErrorLogEvent = new Error_Log_Event__e();

        anErrorLogEvent.Additional_Info__c = errorLog.Additional_Info__c;
        anErrorLogEvent.DML_Exception_Details__c = errorLog.DML_Exception_Details__c;
        anErrorLogEvent.Error_Type__c = errorLog.Error_Type__c;
        anErrorLogEvent.Message__c = errorLog.Message__c;
        anErrorLogEvent.Running_User__c = UserInfo.getUserId();
        anErrorLogEvent.Caller__c = errorLog.Caller__c;
        anErrorLogEvent.Record_Id__c = errorLog.Record_Id__c;
        anErrorLogEvent.Short_Description__c = errorLog.Short_Description__c;
        anErrorLogEvent.Http_End_Point__c = errorLog.Http_End_Point__c;
        anErrorLogEvent.Http_Method__c = errorLog.Http_Method__c;
        anErrorLogEvent.Http_Status_Code__c = errorLog.Http_Status_Code__c;
        anErrorLogEvent.Http_Request__c = errorLog.Http_request__c;
        EventBus.publish(anErrorLogEvent);
    }
    

    public static void logCalloutErrors(Exception ex, HttpRequest req, HttpResponse res) {
        Http_Callout_Setting__mdt calloutSetting = HttpCalloutBuilder.getCalloutSetting(req.getEndpoint(), req.getMethod());
        System.debug('+++callout setting: ' + calloutSetting);
        if (calloutSetting == null || !calloutSetting.Skip_Error_Log__c) {
            Error_Log__c errorLog = new Error_Log__c();
           
            if (req != null) {
                errorLog.Http_End_Point__c = req.getEndpoint();
                errorLog.Http_Method__c = req.getMethod();
                errorLog.Http_Request__c = req.getBody();
                if (String.isNotBlank(errorLog.Http_Request__c) && errorLog.Http_Request__c.length() > Constant.TEXTAREA_LONG_MAX_LENGTH) {
                    errorLog.Http_Request__c = errorLog.Http_Request__c.substring(0, Constant.TEXTAREA_LONG_MAX_LENGTH);
                }
            }
            if (res != null) {
                errorLog.Http_Status_Code__c = String.valueOf(res.getStatusCode());
                errorLog.Additional_Info__c = res?.getBody();
            }
            errorLog.Running_User__c = UserInfo.getUserId();
            errorLog.Error_Type__c = ex.getTypeName();
            errorLog.Short_Description__c = String.isNotBlank(ex.getMessage()) && ex.getMessage().length() > 255 ? ex.getMessage().substring(0, 255) : ex.getMessage();
            errorLog.Message__c = 'Error Message\r\n------------\r\n' + ex.getMessage() + '\r\nStack Trace\r\n------------\r\n' + ex.getStackTraceString();

            publishErrorLogEvent(errorLog);

            if (!suppressException) {
                throw ex;
            }
        }
    }
    
    
    // inner class for error description 
    public class ErrorInfo{
        public String shortDesc;
        public String recordId;
        public String caller;
        public String addInfo;
        public ErrorInfo(String shortDesc, String recordId, String caller, String addInfo){
            this.shortDesc = shortDesc;
            this.recordId = recordId;
            this.caller = caller;
            this.addInfo = addInfo;
        }
    }
}