src/frameworks/error-logger/main/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Apex errors and can be used as a general logger to track integration callouts and callins.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Err-{0}</displayFormat>
        <label>Error Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/frameworks/error-logger/main/objects/Error_Log__c/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <description>Additional Information logged by the developer</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Additional Information logged by the developer</inlineHelpText>
    <label>Additional Info</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log__c/fields/Caller__c.field-meta.xml
<CustomField>
    <fullName>Caller__c</fullName>
    <description>The class/flow which was involved for this error.
PLANHUB-114531.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Caller</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log__c/fields/DML_Exception_Details__c.field-meta.xml
<CustomField>
    <fullName>DML_Exception_Details__c</fullName>
    <description>List and details of all DML exceptions including the record ID and fields that errored</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>List and details of all DML exceptions including the record ID and fields that errored</inlineHelpText>
    <label>DML Exception Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/error-logger/main/objects/Error_Log__c/fields/Error_Type__c.field-meta.xml
<CustomField>
    <fullName>Error_Type__c</fullName>
    <description>Returns the type of exception, such as DmlException, ListException, MathException, and so on</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Returns the type of exception, such as DmlException, ListException, MathException, and so on</inlineHelpText>
    <label>Error Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/error-logger/main/objects/Error_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The error message and stack trace for the error</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The error message and stack trace for the error</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>The involved records e.g. Account Id, Financial Account Id, etc
PLANHUB-114531</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log__c/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who initiated the action that caused the error</description>
    <inlineHelpText>User who initiated the action that caused the error</inlineHelpText>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/frameworks/error-logger/main/objects/Error_Log__c/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <description>Short description for the error, (e.g. OBR Submission Error: Create Request Failed: DUPLICATE_CUSTODIAN_ACCOUNT_ID) will be easy for reporting and querying.
PLANHUB-114531</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Short Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/Error_Log_Event__e.object-meta.xml
<CustomObject>
    <description>AP-86705: Create Salesforce platform events for creating error logs in salesforce.</description>
    <label>Error Log Event</label>
    <pluralLabel>Error Log Events</pluralLabel>
</CustomObject>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <description>AP-86705: Create Salesforce platform events for creating error logs in salesforce.</description>
    <label>Additional Info</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/fields/Caller__c.field-meta.xml
<CustomField>
    <fullName>Caller__c</fullName>
    <description>The class/flow which was involved for this error.
PLANHUB-114531</description>
    <label>Caller</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/fields/DML_Exception_Details__c.field-meta.xml
<CustomField>
    <fullName>DML_Exception_Details__c</fullName>
    <description>AP-86705: Create Salesforce platform events for creating error logs in salesforce.</description>
    <label>DML Exception Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/fields/Error_Type__c.field-meta.xml
<CustomField>
    <fullName>Error_Type__c</fullName>
    <description>AP-86705: Create Salesforce platform events for creating error logs in salesforce.</description>
    <label>Error Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>AP-86705: Create Salesforce platform events for creating error logs in salesforce.</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/error-logger/main/objects/Error_Log_Event__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>The involved records e.g. Account Id, Financial Account Id, etc
PLANHUB-114531</description>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <description>AP-86705: Create Salesforce platform events for creating error logs in salesforce.</description>
    <label>Running User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log_Event__e/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <description>Short description for the error, (e.g. OBR Submission Error: Create Request Failed: DUPLICATE_CUSTODIAN_ACCOUNT_ID) will be easy for reporting and querying.
PLANHUB-114531</description>
    <label>Short Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/classes/ErrorLogEventTriggerHandlerTest.cls
@isTest
private class ErrorLogEventTriggerHandlerTest {
    
    private static final String TESTSTRING = 'Test';
    
    @isTest
    static void testException(){
        Boolean bDoesFail = false;
        try{
            Error_Log_Event__e anErrorLogEvent = new Error_Log_Event__e();
            anErrorLogEvent.Error_Type__c = 'TriggerExceptionTest';
            
            insert anErrorLogEvent;
        }catch(Exception e){
            bDoesFail = true;
            System.debug('exception '+e.getTypeName());
        }
        System.assert(bDoesFail, 'Error_Log_Event__e exception test should throw an exception.');
    }
    
    @isTest
    static void testErrorLogEventTriggerInsert(){
        ErrorLogger.suppressException = true;
        try{
            Test.startTest();
            
            ErrorLogger.logError(new LoggedException(), 'ErrorLogEventTriggerHandlerTest.testErrorLogEventTriggerInsert');
            
            Test.stopTest();
            
            ErrorLogger.suppressException = false;
        }catch(Exception e){
            System.assert(false, 'Unexpected error in ErrorLogEventTriggerHandlerTest.testErrorLogEventTriggerInsert '+e.getMessage());
        }
        
        List<Error_Log__c> lstErrorLog = [SELECT Id, Name, Additional_Info__c FROM Error_Log__c];
        
        System.assertEquals('ErrorLogEventTriggerHandlerTest.testErrorLogEventTriggerInsert', lstErrorLog[0].Additional_Info__c);
    }
    
    @isTest
    static void testErrLogEvtTriggerAdditionalFields(){
        ErrorLogger.suppressException = true;
        try{
            Test.startTest();
            
            ErrorLogger.ErrorInfo info = new ErrorLogger.ErrorInfo(TESTSTRING,TESTSTRING,TESTSTRING,null);
            ErrorLogger.logError(info,new LoggedException());
            
            Test.stopTest();
            
            ErrorLogger.suppressException = false;
        }catch(Exception e){
            System.assert(false, 'Unexpected error in ErrorLogEventTriggerHandlerTest.testErrorLogEventTriggerInsert '+e.getMessage());
        }
        
        List<Error_Log__c> lstErrorLog = [SELECT Id, Name, Additional_Info__c, DML_Exception_Details__c, Error_Type__c, Message__c,
                                          Running_User__c, Caller__c, Record_Id__c, Short_Description__c FROM Error_Log__c];
        
        
        System.assert(String.isNotBlank(lstErrorLog[0].Caller__c), 'Caller is not null');
        System.assert(String.isNotBlank(lstErrorLog[0].Record_Id__c), 'Record Id is not null');
        System.assert(String.isNotBlank(lstErrorLog[0].Short_Description__c), 'Short Description is not null');
    }
    
}