src/frameworks/error-logger/main/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Apex errors and can be used as a general logger to track integration callouts and callins.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Err-{0}</displayFormat>
        <label>Error Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/frameworks/error-logger/main/objects/Error_Log__c/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <description>Additional Information logged by the developer</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Additional Information logged by the developer</inlineHelpText>
    <label>Additional Info</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log__c/fields/Caller__c.field-meta.xml
<CustomField>
    <fullName>Caller__c</fullName>
    <description>The class/flow which was involved for this error.
PLANHUB-114531.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Caller</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log__c/fields/DML_Exception_Details__c.field-meta.xml
<CustomField>
    <fullName>DML_Exception_Details__c</fullName>
    <description>List and details of all DML exceptions including the record ID and fields that errored</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>List and details of all DML exceptions including the record ID and fields that errored</inlineHelpText>
    <label>DML Exception Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/error-logger/main/objects/Error_Log__c/fields/Error_Type__c.field-meta.xml
<CustomField>
    <fullName>Error_Type__c</fullName>
    <description>Returns the type of exception, such as DmlException, ListException, MathException, and so on</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Returns the type of exception, such as DmlException, ListException, MathException, and so on</inlineHelpText>
    <label>Error Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log__c/fields/Http_Request__c.field-meta.xml
<CustomField>
    <fullName>Http_Request__c</fullName>
    <description>This field stores request payload</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>Http Request Payload</inlineHelpText>
    <label>Http Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/error-logger/main/objects/Error_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The error message and stack trace for the error</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The error message and stack trace for the error</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>The involved records e.g. Account Id, Financial Account Id, etc
PLANHUB-114531</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/objects/Error_Log__c/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who initiated the action that caused the error</description>
    <inlineHelpText>User who initiated the action that caused the error</inlineHelpText>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/frameworks/error-logger/main/objects/Error_Log__c/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <description>Short description for the error, (e.g. OBR Submission Error: Create Request Failed: DUPLICATE_CUSTODIAN_ACCOUNT_ID) will be easy for reporting and querying.
PLANHUB-114531</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Short Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/Error Logger/main/classes/ErrorLoggerTest.cls
@isTest
public class ErrorLoggerTest {
    
    private static final String TESTSTRING = 'Test';
    public virtual class TestException extends Exception {}

    static testMethod void testLogError1() {
        Test.startTest();
        try {
        	OpportunityLineItem oli = new OpportunityLineItem(Description  = 'Test');
            insert oli;    
        } catch (Exception ex) { 
            try {
            	ErrorLogger.logError(ex);
            } Catch (Exception ex1){
                //Do Nothing, this is needed so that the Inner exception in ErrorLogger does not fail the test method.
            }
        }
        System.assertEquals(true,ErrorLogger.isTestRun);
        
        Test.stopTest();
    }
    
    static testMethod void testLogError2() {
        Test.startTest();
        String addInfo = 'Addition Info';
        try {
            OpportunityLineItem oli = new OpportunityLineItem(Description  = 'Test');
            insert oli; 
        } catch (Exception ex) {
            try {
            	ErrorLogger.logError(ex, addInfo);
            } Catch (Exception ex1){
                //Do Nothing, this is needed so that the Inner exception in ErrorLogger does not fail the test method.
            }
        }
        System.assertEquals(true,ErrorLogger.isTestRun);
        
        Test.stopTest();
    } 
    
    static testMethod void testLogErrorWithoutException() {
        Test.startTest();
        try{
            String addInfo = 'Additional Info';
            ErrorLogger.logError(addInfo);
        }catch(Exception e){
            System.debug('Catching the dexception.');
        }    
        System.assertEquals(true,ErrorLogger.isTestRun);
        
        Test.stopTest();
    }
    
    static testMethod void testlogDetailedError() {
        ErrorLogger.suppressException = true;
        try{
            Test.startTest();
            
            ErrorLogger.logDetailedError(TESTSTRING, TESTSTRING, TESTSTRING, null);
            
            Test.stopTest();
            
            ErrorLogger.suppressException = false;
        }catch(Exception e){
            System.assert(false, 'Unexpected error in ErrorLogEventTriggerHandlerTest.testErrorLogEventTriggerInsert '+e.getMessage());
        }
        
        List<Error_Log__c> lstErrorLog = [SELECT Id, Name, Additional_Info__c, DML_Exception_Details__c, Error_Type__c, Message__c,
                                          Running_User__c, Caller__c, Record_Id__c, Short_Description__c FROM Error_Log__c];
        
        
        System.assert(String.isNotBlank(lstErrorLog[0].Caller__c), 'Caller is not null');
        System.assert(String.isNotBlank(lstErrorLog[0].Record_Id__c), 'Record Id is not null');
        System.assert(String.isNotBlank(lstErrorLog[0].Short_Description__c), 'Short Description is not null');
    }
    
    static testMethod void testLogErrorWithoutErrWrapper() {
        ErrorLogger.suppressException = true;
        try{
            Test.startTest();
            
            ErrorLogger.ErrorInfo info = new ErrorLogger.ErrorInfo(TESTSTRING,TESTSTRING,TESTSTRING,null);
            ErrorLogger.logError(info,new LoggedException());
            
            Test.stopTest();
            
            ErrorLogger.suppressException = false;
        }catch(Exception e){
            System.assert(false, 'Unexpected error in ErrorLogEventTriggerHandlerTest.testErrorLogEventTriggerInsert '+e.getMessage());
        }
        
        List<Error_Log__c> lstErrorLog = [SELECT Id, Name, Additional_Info__c, DML_Exception_Details__c, Error_Type__c, Message__c,
                                          Running_User__c, Caller__c, Record_Id__c, Short_Description__c FROM Error_Log__c];
        
        
        System.assert(String.isNotBlank(lstErrorLog[0].Caller__c), 'Caller is not null');
        System.assert(String.isNotBlank(lstErrorLog[0].Record_Id__c), 'Record Id is not null');
        System.assert(String.isNotBlank(lstErrorLog[0].Short_Description__c), 'Short Description is not null');
    }
    @isTest
    static void testSkipCalloutErrors() {

        insert new Http_Callout_Control__c (
            Http_Callout_Setting_Name__c = 'Test_Callout_Setting'
        );
        Test.setMock(HttpCalloutMock.class, new Five9SMSServiceHttpCalloutMock());

        try{
            Test.startTest();

            HttpRequest req = new HttpRequest();
            req.setHeader('Authorization', 'TestBearerToken ');
            req.setHeader('Content-Type', 'application/json');
            req.setEndpoint('test/callout/setting') ;
            req.setMethod('GET');

            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{ "Test": "test" }');
            res.setStatusCode(200);

            
            TestException ex = new TestException('Error In Callout');

            ErrorLogger.logCalloutErrors(ex,req,res );

            Test.stopTest();
       
        }catch(Exception e){
            Assert.isTrue(false, 'erorr was thrown, error should be skipped');
        }
        
    }

    @isTest
    static void testLogCalloutErrors() {

        insert new Http_Callout_Control__c (
            Http_Callout_Setting_Name__c = 'Test_Callout_Setting'
        );
        Test.setMock(HttpCalloutMock.class, new Five9SMSServiceHttpCalloutMock());

        try{
            Test.startTest();

            HttpRequest req = new HttpRequest();
            req.setHeader('Authorization', 'TestBearerToken ');
            req.setHeader('Content-Type', 'application/json');
            req.setEndpoint('test/skip/callout/setting') ;
            req.setMethod('POST');
            req.setBody('{sample request body}');

            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{ "Test": "test" }');
            res.setStatusCode(200);

            
            TestException ex = new TestException('Error In Callout');

            ErrorLogger.logCalloutErrors(ex,req,res );
            Assert.isTrue(false, 'erorr should be thrown by previous line');
            Assert.isTrue('{sample request body}' == [Select Http_Request__c from Error_Log__c].get(0).Http_Request__c);
            Test.stopTest();
       
        }catch(Exception e){
            Assert.isTrue(true);
        }
        
    }
}